### ISSUE TITLE
[BUG] - Cluster options on the top left corner aren't working properly

### ISSUE THREAD

**Issue by cthotadi** [cars10/elasticvue#103]
**READ BEFORE OPENING AN ISSUE**
Before you submit an issue please try to reset elasticvue and see if you can reproduce the problem.
To reset please click `Disconnect and reset` in the footer, this will reset all your saved filters and you have to reconnect to your cluster.
Proceed and open an issue if your problem persists.

**Description**
**Problem 1:**
-  While adding a cluster (v6.8.10) by providing a name, credentials and host, on clicking connect it loads infinitely and the name changes to `default cluster`  while it is loading. But if I close and refresh, the cluster is getting added

**Problem 2:**
- I have added many clusters nearly 11 to elasticvue. I am deleting some no longer used clusters from elastivue but upon deleting it deletes the wrong cluster. For suppose If I am selecting cluster 5 to get deleted, cluster 6 or some other is getting deleted

**Problem 3:**
- Try to switch between clusters does not work. If I want to switch between cluster by clicking on a different cluster, the data isn't refreshed and the drop down does not get closed. Upon refreshing the switch is happening

**Steps To Reproduce**
List the steps to reproduce your problem:
**Problem 1:**
1. Open elasticvue
2. Click on "Add Cluster"
3. Provide the cluster name, credentials and host
4. Click "Test Connection"
5. Now, Click on "Connect"

**Problem 2:**
1. Open elasticvue
2. Ensure to have more clusters at least 3
3. Try to sort on the cluster name
4. Click to delete any cluster, an Alert will be opened 
5. Upon checking the alert, you would observe that wrong cluster is getting deleted

**Problem 3:**
1. Open elasticvue
2. Ensure to have more clusters at least 2
3. Connect to one cluster and switch to another

**Screenshots**

**Environment (please include the following information):**
* Elasticsearch version: 6.8.10
* Operating system: Windows 10 Enterprise 21H2
* Browser + version: Chrome 101.0.4951.41 (Official Build) (64-bit)
* Elasticvue version: 0.40.0
* How are you running elasticvue? (docker, browser extension, web app): Chrome Extension

**Additional context**
Anything else?

**Comment by cars10** [comment]
Sorry for the inconvenience! This was some very sloppy testing. Should be fixed now.

**Comment by cthotadi** [comment]
@cars10 thanks for the quick fix and release of new version. When I tested the new version Problem 2 is still happening. Please view the screenshot below
![InkedScreenshot_1_LI](https://user-images.githubusercontent.com/32841391/166411748-b154dc98-3e5a-44fb-aa3f-544c888f58ba.jpg)

**Comment by cars10** [comment]
Oooh i could not reproduce this one, thanks for the screenshot! Ofc this breaks when you order the clusters by name, i will look into it. Thanks!
