### ISSUE TITLE
Missing uuid for old versions of elasticsearch

### ISSUE THREAD

**Issue by wojiaoxiaomayun** [cars10/elasticvue#182]
The new version of REST does not support lower version operations anymore。thanks for you。

**Comment by wojiaoxiaomayun** [comment]
Just add it again and it will be useful

**Comment by cars10** [comment]
Hey, can you please elaborate what exactly you are missing? I dont understand your request.

**Comment by wojiaoxiaomayun** [comment]
![1704187167182](https://github.com/cars10/elasticvue/assets/30283623/bfa60220-f050-4254-90ab-a6b3b304f18a)
![1704188388520](https://github.com/cars10/elasticvue/assets/30283623/b6c6ef88-c978-420f-bedb-cc78a2e74642)
Sorry, this is my problem because the version in the edge store is still 1.0.0, which caused the old version of the ES client I added before 1.0.0 to not have UUID, resulting in an issue

**Comment by cars10** [comment]
Thanks! This should be fixed if you remove and re-add your cluster.

**Comment by wojiaoxiaomayun** [comment]
Indeed, after the updated version, the original rest query history is gone, and it still exists in indexdb. Because a new db was created, the original db lost its function. This is not a big problem, and there is no need to modify it. It's just a pity that I have many useful histories that I need to redo and add. Thank you very much for developing this software.

**Comment by cars10** [comment]
Fixed in `1.0.2`.
