### ISSUE TITLE
"Filter ONLY current page" is not working in extension

### ISSUE THREAD

**Issue by pWoLiAn** [cars10/elasticvue#244]
_Disconnect does not fix the issue_

**Description**
![image](https://github.com/user-attachments/assets/3211565d-15c4-4c2d-af9b-bfdd58d73cd0)
this filter does not work on the search page

**Steps To Reproduce**
List the steps to reproduce your problem:
1. Open elasticvue in browser
2. Click on any of the indices
3. Search with default values
4. Try to filter using given box

**Environment (please include the following information):**
* Elasticsearch version: 7.4.0
* Operating system: Windows 11
* Browser + version: Google chrome (Version 126.0.6478.127 (Official Build) (64-bit))
* Elasticvue version: 1.0.9
* How are you running elasticvue? extension

**Comment by cars10** [comment]
Can you add some example data that you are trying to filter?

**Comment by pWoLiAn** [comment]
For eg, one of the fields in the doc has "Microsoft" in it but when i filter for "Microsoft", nothing happens.

**Comment by cars10** [comment]
I cannot reproduce this. Do you see any errors in the browser console?

**Comment by pWoLiAn** [comment]
found this in the console. not sure if it is relevant.
```
 TypeError: o[r].toString is not a function
    at assets/index-DzMw0zuL.js:70:11194
    at Array.some (<anonymous>)
    at assets/index-DzMw0zuL.js:70:11137
    at Proxy.filter (<anonymous>)
    at wo (assets/index-DzMw0zuL.js:70:11125)
    at assets/index-DzMw0zuL.js:90:39913
    at eo.fn (assets/index-DzMw0zuL.js:10:9419)
    at eo.run (assets/index-DzMw0zuL.js:10:1517)
    at get value (assets/index-DzMw0zuL.js:10:9664)
    at T0 (assets/index-DzMw0zuL.js:10:1674)
```

**Comment by cars10** [comment]
This seems to be the bug that you encounter. Can you provide the mappings for the index where filtering does not work? You can redact anything business relevant, i am interested in the types.

**Comment by pWoLiAn** [comment]
[mappings.json](https://github.com/user-attachments/files/16345821/mappings.json)
issue is seen for all indices. these are the mappings for one of the indices. i was trying to filter using the name field

**Comment by cars10** [comment]
Thanks! Fixed in `1.0.10`.

**Comment by j0e1-scaria** [comment]
looks like the issue is still not fixed. the filtering still doesn't work and i see the same error in the console:
```
TypeError: o[r].toString is not a function[FilterInput.vue:22]
    at filters.ts:25:35
    at Array.some (<anonymous>)
    at filters.ts:23:26
    at Proxy.filter (<anonymous>)
    at xo (filters.ts:22:18)
    at SearchResultsTable.ts:93:12
    at no.fn (reactivity.esm-bundler.js:998:13)
    at no.run (reactivity.esm-bundler.js:177:19)
    at get value (reactivity.esm-bundler.js:1010:102)
    at q0 (reactivity.esm-bundler.js:195:19)
```

**Comment by cars10** [comment]
@joel-scaria-hpe-gh can you provide some sample data that looks like it might cause the issue? It works for every kind of data that i tested.

**Comment by joel-scaria-hpe-gh** [comment]
@cars10 Before that, can you give me an idea on what this filter/feature actually does along with an example? I couldn't find anything specific in the documentation. Just wanted to make sure that I'm not using it incorrectly

**Comment by joel-scaria-hpe-gh** [comment]
I was not aware you had mind-reading capabilities 🙂
