### ISSUE TITLE
[BUG] Can't connect to ES 7.1.1

### ISSUE THREAD

**Issue by iDmple** [cars10/elasticvue#5]
**Description**
I can't cannot to my ES instance since I upgraded to 7.1.1 from 6.7.1

**Steps To Reproduce**
List the steps to reproduce your problem:
1. Open elasticvue
2. Click on TEST CONNECTION
3. I get
```
Could not connect. Please make sure that
Your cluster is reachable via https://elastic:xxx@es.xxx.xx
You added the correct settings to your elasticserach.yml and restarted your cluster
Either your cluster is not reachable or you did not configure CORS correctly.
```
Interestingly, when doing right click, inspect, I get 200 OK and the json answer from ES in the network tab:
```
{
  "name" : "xxx",
  "cluster_name" : "xxx",
  "cluster_uuid" : "xxx",
  "version" : {
    "number" : "7.1.1",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "7a013de",
    "build_date" : "2019-05-23T14:04:00.380842Z",
    "build_snapshot" : false,
    "lucene_version" : "8.0.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

Of course I already added the necessary config in elasticsearch.yml, and it was working perfectly before the upgrade from 6.7.1.

**Environment (please include the following information):**
* Operating system: CentOS7
* Browser + version: Chrome 75.0.3770.80
* Elasticvue version: latest docker image
* How are you running elasticvue? docker

Am I missing anything, or could this be due to the new security features of 7.1.1?

**Comment by cars10** [comment]
Hey, thanks for your report. This is probably related to new security features or the elasticsearch client i currently use is too old.

Sadly i am on vacation right now and cannot check the issue - I will take a look in 3 days and report back :)

Sorry for the inconvenience.

**Comment by iDmple** [comment]
Many thanks for your answer. Please enjoy your holidays! I'll gladly provide any details you need to reproduce this bug after you return.

Cheers

**Comment by cars10** [comment]
Thanks again for the details bug report, i just published a fix for this issue (`v0.10.2`). 
An updated docker image and chrome extension should be available in the next hour or so :) 

Let me know if you encounter another issue.

**Comment by iDmple** [comment]
Many thanks. I confirm that it works now!
Cheers

**Comment by JaldeaR** [comment]
I believe the same connection issue is back.

```
Could not connect. Please make sure that

    Your cluster is reachable via https://xxx:9200/
    You added the correct settings to your elasticsearch.yml and restarted your cluster 

Either your cluster is not reachable or you did not configure CORS correctly.
```

When doing it manually via curl in terminal:


```
{
  "name" : "xxx",
  "cluster_name" : "xxx",
  "cluster_uuid" : "xxx",
  "version" : {
    "number" : "8.2.0",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "b174af62e8dd9f4ac4d25875e9381ffe2b9282c5",
    "build_date" : "2022-04-20T10:35:10.180408517Z",
    "build_snapshot" : false,
    "lucene_version" : "9.1.0",
    "minimum_wire_compatibility_version" : "7.17.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "You Know, for Search"
}
```

    Operating system: Ubuntu 22.04
    Browser + version: Firefox 100.0.1(64bit)
    Elasticvue version: latest docker image
    How are you running elasticvue? docker

If i'm missing information please let me know.

**Comment by cars10** [comment]
You are using elasticsearch 8 so you are probably using ssl. Do you use a trusted certificate? Please check [https://github.com/cars10/elasticvue/wiki/Elasticsearch-8](https://github.com/cars10/elasticvue/wiki/Elasticsearch-8)
